server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.0.50.191:3306/demo?serverTimezone=UTC&useSSL=false
    username: root
    password: root123@eCloud
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.ecloud.entity
  mapper-locations: classpath:mapper/*.xml